directories:
  output: build
  buildResources: build
productName: gos24-desktop
appId: kz.gos24
publish:
  - provider: github
    owner: baha96
    private: false
files:
  - filter:
      - dist/electron/**/*
dmg:
  contents:
    - x: 410
      'y': 150
      type: link
      path: /Applications
    - x: 130
      'y': 150
      type: file
mac:
  icon: icons/icon.icns
win:
  icon: icons/icon1.ico
linux:
  icon: icons
electronVersion: 2.0.18
